# Generated by Django 3.1.1 on 2020-10-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0002_customer_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logs',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
