# Generated by Django 3.1.1 on 2020-10-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cust', '0007_order_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='cust.Tag'),
        ),
    ]
